name: Nightly

on:
  # Runs every night at 2 AM
  schedule:
    - cron: '0 2 * * *'
  # Manaual trigger
  workflow_dispatch:

concurrency:
  group: nightly-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup
        uses: ./.github/actions/setup-node

      - name: Build framework
        run: pnpm build

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test

      - name: Publish framework to Verdaccio
        run: |
          pnpm verdaccio:init &
          npx wait-on@8.0.1 http://localhost:4873
          pnpm verdaccio:publish

      - name: Run end-to-end tests
        run: |
          NPM_CONFIG_REGISTRY=http://localhost:4873 pnpm e2e

  build-android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bundler: [metro, repack]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v@4.2.2

      - name: Setup
        uses: ./.github/actions/setup-node

      - name: Install Java
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          java-version: 17
          distribution: adopt

      - name: Build framework
        run: pnpm build

      - name: Publish framework to Verdaccio
        run: |
          pnpm verdaccio:init &
          npx wait-on@8.0.1 http://localhost:4873
          pnpm verdaccio:publish

      - name: Deploy template
        run: |
          cd ..
          NPM_CONFIG_REGISTRY=http://localhost:4873 pnpm create rock \
            --registry http://localhost:4873 \
            NightlyDeploy \
            --template=default \
            --platform=ios --platform=android \
            --bundler=${{ matrix.bundler }} \
            --remote-cache-provider=github-actions

          cd NightlyDeploy
          NPM_CONFIG_REGISTRY=http://localhost:4873 \
            NPM_CONFIG_NODE_LINKER=hoisted \
            pnpm install

      - name: Build Android template
        run: |
          cd ../NightlyDeploy
          pnpm rock build:android

  build-ios:
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_16.4.0.app/Contents/Developer
    strategy:
      matrix:
        bundler: [metro, repack]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup
        uses: ./.github/actions/setup-node

      - name: Build framework
        run: pnpm build

      - name: Publish framework to Verdaccio
        run: |
          pnpm verdaccio:init &
          npx wait-on@8.0.1 http://localhost:4873
          pnpm verdaccio:publish

      - name: Deploy template
        run: |
          cd ..
          NPM_CONFIG_REGISTRY=http://localhost:4873 pnpm create rock \
            --registry http://localhost:4873 \
            NightlyDeploy \
            --template=default \
            --platform=ios --platform=android \
            --bundler=${{ matrix.bundler }} \
            --remote-cache-provider=github-actions

          cd NightlyDeploy
          NPM_CONFIG_REGISTRY=http://localhost:4873 \
            NPM_CONFIG_NODE_LINKER=hoisted \
            pnpm install

      - name: Build iOS template
        run: |
          cd ../NightlyDeploy
          pnpm rock build:ios --verbose \
            --destination=simulator
